### ISSUE TITLE
Foreign key 'offers_categories' error in while migrating offers table

### ISSUE THREAD

**Issue by aminetiyal** [BuildForSDGCohort2/Team-248-Backend#28]
`SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table 'offers' add constraint 'offers_category_id_foreign' foreign key ('category_id') references 'offers_categories' ('id'))`

https://github.com/BuildForSDGCohort2/Team-248-Backend/blob/310ea83fcc00de5527463bd06b64afbb748375fd/database/migrations/2020_08_24_210121_create_offers_table.php#L21

**Comment by aminetiyal** [comment]
#26

**Comment by mnourrhan** [comment]
@aminetiyal The issue fixed in this [pull request](https://github.com/BuildForSDGCohort2/Team-248-Backend/pull/26) and waiting for reviewing and merging. @RanaEmad  @John0Isaac
